export const bindungsanalyseMuenchenText = `
Aus Sicht der pränatalen Psychologie entwickeln sich eine sichere Bindung und daraus unser Vertrauen in die Welt (das sog. Urvertrauen) bereits vorgeburtlich. So gibt es bei einem guten Kontakt zwischen Mutter und ungeborenem Kind schon sehr frühe Erfahrungen von psychischer Verbundenheit, Willkommen-Sein, von Sicherheit und von Versorgt-Sein. Diese Erfahrungen werden nonverbal im sogenannten Zellgedächtnis gespeichert und bilden eine wichtige Grundlage für eine gesunde psychische und körperliche Entwicklung.

Die pränatale Bindungsanalyse ist eine Form der Schwangerschaftsbegleitung, die Ihnen die Möglichkeit bietet, bereits während der Schwangerschaft eine sichere Bindung zu Ihrem Baby aufzubauen und sich mit ihm gemeinsam auf das Wunder der Geburt vorzubereiten.

Im Mittelpunkt der Bindungsanalyse steht die Begegnung mit dem ungeborenen Kind: In einem Zustand tiefer Entspannung wird die Aufmerksamkeit der Mutter auf die Gebärmutter konzentriert und über diesen Weg mit dem Baby kommuniziert. Mutter und Kind tauschen sich dabei am häufigsten über Bilder, stille Dialoge oder über die Wahrnehmung von Körperempfindungen aus.

Im Kontakt mit ihrem ungeborenen Kind lernt die Mutter sich in die Welt ihres Babys einzufühlen, seine Bedürfnisse und Signale wahrzunehmen und feinfühlig darauf zu reagieren. Dadurch erlebt sich das Baby emotional gesehen und getragen und es kann ein klares Gefühl für sich Selbst und seinen Körper entwickeln.

Gleichzeitig geht es bei der Bindungsanalyse darum, den sensiblen Prozess des Mutter-Werdens einfühlsam zu begleiten: Durch den innigen Austausch mit dem Baby kann die Mutter ein zunehmendes Gespür für ihren eigenen Körper sowie ein wachsendes Vertrauen in sich selbst und in die natürlichen Vorgänge von Schwangerschaft und Geburt entwickeln. Auf diese Weise kann ein sanftes und sicheres Hineinwachsen in das Mutter-Sein sowie eine angstfreie Vorbereitung auf die Geburt gelingen.
`.trim();

export const bindungsanalyseFuerWenInfo = `
<h5>für wen ist die Bindungsanalyse geeignet?</h5><p>Die Bindungsanalyse eignet sich für alle Frauen, die den Wunsch haben, bereits vor der Geburt mit ihrem Baby in einen sehr berührenden und tiefen Kontakt zu treten und ihr Vertrauen in ihren Körper und in ihre natürliche mütterliche Kompetenz zu stärken.</p><p> </p><p>Besonders tragend kann die Bindungsanalyse sein, wenn Sie sich in Ihrer aktuellen Schwangerschaft emotional oder körperlich belastet fühlen.</p><p> </p><p>Gründe hierfür können eine stressige Lebenssituation, körperliche Beschwerden (z.B. vorzeitige Kontraktionen, Blutungen, Frühgeburtsrisiko), Ängste oder Loyalitätskonflikte gegenüber Erstgeborenen sein. </p><p> </p><p>Auch vorangegangene schwierige Schwangerschafts- und Geburtserfahrungen (wie z.B. der Verlust eines Kindes, eine Geburtseinleitung, Früh- oder Kaiserschnittgeburten) können emotional sehr tiefgreifend sein und bei einer erneuten Schwangerschaft dem Bindungsaufbau zum Baby im Wege stehen.</p><p> </p><p>In der Bindungsanalyse haben Sie die Möglichkeit, individuell und einfühlsam von mir begleitet, derartige belastende Erfahrungen zu verarbeiten, Stress zu reduzieren und Schritt für Schritt einen Kontakt zur Ihrem Baby aufzubauen. </p><p> </p><p>Auch bei bisher unerfülltem Kinderwunsch kann die Bindungsanalyse emotionale Entlastung schaffen und eventuelle psychische Blockaden lösen.</p><p>‍</p>
`.trim();

export const bindungsanalyseErfahrungenInfo = `
<h5>Erfahrungen mit der Bindungsanalyse</h5><p>Durch die Bindungsanalyse können Mutter und Kind zu einem guten Team zusammenwachsen. Die Geburten können dadurch mit weniger Unsicherheiten und Ängsten verbunden sein: </p><p> </p><ul role="list"><li>die Geburten können natürlicher und leichter verlaufen, wodurch die Notwendigkeit für geburtsunterstützende Maßnahmen oder medizinische Eingriffe sinken kann</li><li>die Geburten beginnen meist um den errechneten Geburtstermin</li></ul><p>Babys die bereits im Mutterleib sicher gebunden sind, weisen eine erhöhte Widerstandfähigkeit gegen Stress sowie gegen seelische und körperliche Erkrankungen auf. </p><p> </p><p>Außerdem verfügen sie über eine hohe Selbstregulationsfähigkeit.</p><p> </p><ul role="list"><li>Schreiattacken sowie Ein- und Durchschlafstörungen können somit deutlich weniger auftreten</li><li>die Babys sind erfahrungsgemäß sehr ausgeglichen und begegnen der Welt mit großer Wachheit und Neugierde</li></ul><p>Da durch die Bindungsanalyse bereits pränatal das positive Erleben der Mutter und das Zutrauen in das Mutter-Sein gefördert wird, können Mütter der Zeit nach der Geburt entspannter und selbstsicherer begegnen.</p><p> </p><p>Nach der Geburt ist die Verständigung mit dem neugeborenen Baby erfahrungsgemäß einfach und gelingt intuitiv. Dies kann sich auch positiv auf die Stillbeziehung zwischen Mutter und Kind auswirken. </p><p>(vgl. hierzu u.a.: G. Schroth (2009): Die Bindungsanalyse nach Raffai und Hidas. Eine Einführung, in: Int. J. Prenatal and Perinatal Psychology and Medicine, Vol. 21, No. 3/4, S. 343-347).</p>
`.trim();
