export const therapieablaufPsychotherapieInfo = `
<p><strong>Psychotherapie:</strong></p><p>In einem Erstgespräch nehmen wir uns Zeit uns gegenseitig kennen zu lernen und Sie bekommen Raum, um Ihre Themen, Anliegen und Wünsche zu formulieren. Darüber hinaus mache ich mir ein erstes Bild über Ihre aktuelle Lebenssituation. Nach diesem ersten Treffen haben Sie dann die Möglichkeit, noch einmal in sich hinein zu fühlen, ob Sie sich von mir im Weiteren begleiten und unterstützen lassen wollen. </p><p> </p><p>Unsere gemeinsame Arbeit findet in Form von Einzelsitzungen in meiner Praxis statt. Die Dauer einer Therapie kann je nach Bedarf und Symptomatik individuell unterschiedlich sein. Erfahrungsgemäß bewährt sich ein regelmäßiger Rhythmus mit Sitzungen in Abständen von 1-2 Wochen. Aber auch hier ist es wichtig, die jeweilige Lebenssituation und Problematik im Einzelnen zu betrachten und gemeinsam eine für Sie stimmige Lösung zu finden. </p>
`.trim();

export const therapieablaufBindungsanalyseInfo = `
<p>‍<strong>Bindungsanalyse:</strong></p><p>Der Beginn einer Bindungsanalyse orientiert sich am individuellen Bedarf. Erfahrungsgemäß ist aber gerade der Anfang einer Schwangerschaft nicht selten mit körperlichen Belastungen oder mit Ängsten um das ungeborene Kind verbunden, weshalb ein Beginn ab der 12. SSW empfehlenswert ist. </p><p> </p><p>Nach einem gegenseitigen Kennenlernen und Vertrauensaufbau finden wöchentlich 1-2 Einzelsitzungen, die sogenannten „Babystunden", statt. Dabei begleite ich Sie und Ihr Baby in der Regel bis zur Abschlussphase (Beginn um die 37. SSW). In dieser bereiten Sie sich mit Ihrem Baby auf den Abschied von der Schwangerschaft und auf die gemeinsame Geburt vor.</p><p>Weitere Informationen finden Sie <a href="/bindungsanalyse-muenchen">hier</a>.</p>
`.trim();

export const therapieablaufKostenInfo = `
<p><strong>Behandlungskosten</strong></p><p>Eine Abrechnung der Behandlungskosten durch Heilpraktiker für Psychotherapie ist mit den gesetzlichen Krankenkassen bisher nicht möglich. Mein Therapie- und Beratungsangebot richtet sich daher ausschließlich an SelbstzahlerInnen. </p><p> </p><p>Als SelbstzahlerIn wird Ihre Therapie bei der Krankenkasse nicht vermerkt, es braucht keine formellen Anträge, wir können jederzeit mit der Arbeit beginnen.</p><p> </p><p>Jeweils am Monatsende erhalten Sie eine Rechnung über die angefallenen Stunden. Eine Barzahlung am Ende jeder Sitzung ist ebenfalls möglich. </p><p> </p><p>Psychotherapie ist nach § 4 Nr. 14 UStG umsatzsteuerfrei.</p>
`.trim();
